// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP9irCRVlDNueffeoRy4tbDgzYNl4ZU0I',
    appId: '1:905832012460:web:bdd9ed36b59ff2de52dd09',
    messagingSenderId: '905832012460',
    projectId: 'firefly-chatroom',
    authDomain: 'firefly-chatroom.firebaseapp.com',
    storageBucket: 'firefly-chatroom.firebasestorage.app',
    measurementId: 'G-D94TWLT9C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuDgNs9OFhAdWDi67D_yLrHdeIfgu-ZM',
    appId: '1:905832012460:android:fcde219ad224960652dd09',
    messagingSenderId: '905832012460',
    projectId: 'firefly-chatroom',
    storageBucket: 'firefly-chatroom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxMabVfaM8ETQgjhmgUHkTzz3fRogz0o',
    appId: '1:905832012460:ios:2a4b3308f0783c8a52dd09',
    messagingSenderId: '905832012460',
    projectId: 'firefly-chatroom',
    storageBucket: 'firefly-chatroom.firebasestorage.app',
    iosBundleId: 'com.example.firefly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxMabVfaM8ETQgjhmgUHkTzz3fRogz0o',
    appId: '1:905832012460:ios:2a4b3308f0783c8a52dd09',
    messagingSenderId: '905832012460',
    projectId: 'firefly-chatroom',
    storageBucket: 'firefly-chatroom.firebasestorage.app',
    iosBundleId: 'com.example.firefly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP9irCRVlDNueffeoRy4tbDgzYNl4ZU0I',
    appId: '1:905832012460:web:390751d8426a1fd052dd09',
    messagingSenderId: '905832012460',
    projectId: 'firefly-chatroom',
    authDomain: 'firefly-chatroom.firebaseapp.com',
    storageBucket: 'firefly-chatroom.firebasestorage.app',
    measurementId: 'G-S44KD00X5B',
  );
}
