// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQcWyvUBSQNKbYvnWRY5fBS8O8VAQldQ0',
    appId: '1:568055092414:web:98a07fbf118844b3b1baef',
    messagingSenderId: '568055092414',
    projectId: 'firefly-11f82',
    authDomain: 'firefly-11f82.firebaseapp.com',
    storageBucket: 'firefly-11f82.firebasestorage.app',
    measurementId: 'G-XBYWPJZDKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD0Kqx54PCaGSgXJMmgykJLfvLxiANihc',
    appId: '1:568055092414:android:997094b7b9e6ace5b1baef',
    messagingSenderId: '568055092414',
    projectId: 'firefly-11f82',
    storageBucket: 'firefly-11f82.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZ4cdKFFkgsWCh6XYq88XdugtCUjqYz8',
    appId: '1:568055092414:ios:1f89bdd6150e518fb1baef',
    messagingSenderId: '568055092414',
    projectId: 'firefly-11f82',
    storageBucket: 'firefly-11f82.firebasestorage.app',
    iosBundleId: 'com.example.firefly',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPZ4cdKFFkgsWCh6XYq88XdugtCUjqYz8',
    appId: '1:568055092414:ios:1f89bdd6150e518fb1baef',
    messagingSenderId: '568055092414',
    projectId: 'firefly-11f82',
    storageBucket: 'firefly-11f82.firebasestorage.app',
    iosBundleId: 'com.example.firefly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQcWyvUBSQNKbYvnWRY5fBS8O8VAQldQ0',
    appId: '1:568055092414:web:8d5df88dd6e75423b1baef',
    messagingSenderId: '568055092414',
    projectId: 'firefly-11f82',
    authDomain: 'firefly-11f82.firebaseapp.com',
    storageBucket: 'firefly-11f82.firebasestorage.app',
    measurementId: 'G-CWT37BWCWT',
  );
}
